/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vivekraja07' at '1/29/17 4:10 PM' with Gradle 3.0
 *
 * @author vivekraja07, @date 1/29/17 4:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
